const fs=require('fs'),vm=require('vm'),assert=require('assert');
const base=require('path').resolve(__dirname,'..')+require('path').sep;
const html=fs.readFileSync(base+'web/index.html','utf8');
class Element{
 constructor(id=''){this.id=id;this.value='';this.hidden=false;this.disabled=false;this.checked=false;this.children=[];this.handlers={};this.textContent='';this.attrs={};this.classList={toggle(){},add(){},remove(){}};this.scrollTop=0;this.scrollHeight=0;this.clientHeight=0;this.dataset={};}
 addEventListener(name,fn){this.handlers[name]=fn;}setAttribute(n,v){this.attrs[n]=v;}removeAttribute(n){delete this.attrs[n];}
 append(...els){this.children.push(...els);}replaceChildren(...els){this.children=els;}querySelector(){if(!this.child)this.child=new Element();return this.child;}querySelectorAll(){return[];}focus(){}scrollIntoView(){}contains(){return false;}
}
const elements={};for(const [,id] of html.matchAll(/id="([^"]+)"/g))elements[id]=new Element(id);
assert(!elements['analysis-max'],'sample limit control must be removed');
assert(!html.includes('60–600'),'sample limit copy must be removed');
assert(!html.includes('AI 深度分析'),'use concrete AI analysis label');
const rels=['friend','family','partner','best_friend'].map(value=>Object.assign(new Element(),{value,checked:value==='friend'}));
const modes=['local','ai'].map(mode=>Object.assign(new Element(),{dataset:{analysisMode:mode}}));
const generic=new Element();const calls=[];let serverState={busy:false,operation:null,status:'ready',sessions:[],logs:[],wechatReady:false,analysisArchive:'',analysisResult:false};
const document={getElementById:id=>{assert(elements[id],`missing DOM id ${id}`);return elements[id];},createElement:()=>new Element(),addEventListener(){},activeElement:null,
 querySelector(sel){if(sel==='meta[name="archive-token"]')return{content:'test'};if(sel==='input[name="relationship"]:checked')return rels.find(x=>x.checked);return generic;},
 querySelectorAll(sel){if(sel==='[data-analysis-mode]')return modes;if(sel==='input[name="relationship"]')return rels;if(sel.startsWith('#analysis-form'))return [...Object.values(elements).filter(x=>x.id.startsWith('analysis-')), ...rels,...modes];return[];}};
const preview={relationshipLabel:'朋友',stats:{messageCount:121},coverage:{mode:'full',totalMessages:121,validTextMessageCount:120,sentMessageCount:120,omittedTextMessages:0,batchCount:2,mediaOnlyMessageCount:1},systemPrompt:'Safe instructions',batches:[{index:1,messageCount:60,systemPrompt:'Safe instructions',payloadText:'{"messages":[{"id":"m1","text":"redacted first"}]}'},{index:2,messageCount:60,systemPrompt:'Safe instructions',payloadText:'{"messages":[{"id":"m120","text":"redacted last"}]}'}],synthesis:{required:true,systemPrompt:'Synthesis evidence rules',payloadTemplate:'{"batchResults":"filled after validated responses"}',description:'Combine validated batch results; recursively group long results.'}};
preview.frameworkProfile={primaryTheory:{name:'社会交换理论'}};
preview.synthesis.intermediateSystemPrompt='Intermediate synthesis psychology rules';
async function fetch(url,opt){const path=url.replace('/api/','');const body=opt.body?JSON.parse(opt.body):undefined;calls.push({path,body});let data={};let ok=true;
 if(path==='config')data={output:'/archives',model:'small',address:'http://127.0.0.1',wechatReady:false};
 else if(path==='state')data=serverState;
 else if(path==='analysis/inspect'){if(body.archive==='bad'){data={error:'invalid archive'};ok=false;}else data={archivePath:body.archive,messageCount:121,dateRange:{start:'2026-01-01',end:'2026-03-01'},participants:[{id:'a',name:'Alice',count:60},{id:'b',name:'Bob',count:61}],quality:{warnings:[],sourceFormat:'qce-chunked-jsonl'}};}
 else if(path==='analysis/prepare')data={previewId:'preview-1',preview:{...preview,batches:preview.batches.map(batch=>({...batch,systemPrompt:batch.systemPrompt+(body.customPrompt?'\nUser focus: '+body.customPrompt:'')}))}};
 else if(path==='analysis/start'){serverState={...serverState,operation:'analyze',status:'complete',analysisResult:true,analysisSummary:{mode:body.mode,relationshipLabel:'朋友',messageCount:120}};data={ok:true};}
 return{ok,json:async()=>data};}
const context=vm.createContext({document,fetch,Option:function(t,v){return Object.assign(new Element(),{textContent:t,value:v});},URL,window:{open(){}},confirm:()=>true,setTimeout:()=>1,clearTimeout(){},console});
vm.runInContext(fs.readFileSync(base+'web/app.js','utf8'),context);
const run=source=>vm.runInContext(source,context);
(async()=>{await new Promise(r=>setImmediate(r));
 run("showView('help')");assert(!elements['help-view'].hidden);assert(elements['export-view'].hidden);assert(elements['analysis-view'].hidden);
 run("openHelp('api')");assert.strictEqual(run('activeView'),'help');assert(html.includes('导出和本地分析不需要 API'));
 run("renderWechatStep({active:true,code:'password',title:'等待授权',detail:'输入 Mac 密码'})");assert(!elements['cancel-wechat'].hidden);assert.strictEqual(elements['wechat-next-actions'].children.length,1);
 run("state={wechatInstalled:true,wechatConnection:{active:true}};refreshReadiness()");assert(elements['init-wechat'].disabled);
 await run('connectQQ()');assert.strictEqual(calls.at(-2).body.action,'prepare-qq');
 run("showView('analysis')");assert(elements['export-view'].hidden);assert(!elements['analysis-view'].hidden);
 elements['analysis-archive'].value='/fake';assert(await run('inspectAnalysisArchive()'));assert(elements['analysis-self'].children.length===3);assert(!run('analysisReady()'));assert(elements['analysis-loaded-detail'].textContent.includes('QQ 分块 JSONL'));
 elements['analysis-self'].value='a';run('invalidateAnalysisPreview()');assert(run('analysisReady()'));
 elements['analysis-custom-prompt'].value='Ignored in local mode';
 for(const rel of rels){for(const r of rels)r.checked=r===rel;await run('prepareAnalysis()');assert(calls.filter(x=>x.path==='analysis/prepare').at(-1).body.relationship===rel.value);assert(calls.filter(x=>x.path==='analysis/prepare').at(-1).body.customPrompt==='');assert(!('maxMessages' in calls.filter(x=>x.path==='analysis/prepare').at(-1).body));assert(calls.filter(x=>x.path==='analysis/start').at(-1).body.mode==='local');}
 const endpoints=[['https://api.vendor.test/v1','https://api.vendor.test/v1/chat/completions'],['https://api.vendor.test/gateway/v2/chat/completions','https://api.vendor.test/gateway/v2/chat/completions'],['https://api.deepseek.com','https://api.deepseek.com/chat/completions'],['https://api.deepseek.com/','https://api.deepseek.com/chat/completions'],['https://api.deepseek.com/v1','https://api.deepseek.com/v1/chat/completions'],['https://api.deepseek.com/v1/','https://api.deepseek.com/v1/chat/completions'],['https://api.deepseek.com/chat/completions','https://api.deepseek.com/chat/completions'],['https://api.deepseek.com/v1/chat/completions/','https://api.deepseek.com/v1/chat/completions'],['http://localhost:8000/v1','http://localhost:8000/v1/chat/completions'],['http://[::1]:8000','http://[::1]:8000/chat/completions']];
 for(const [input,expected] of endpoints)assert.strictEqual(run('normalizeAnalysisEndpoint('+JSON.stringify(input)+')'),expected);
 for(const input of ['not-a-url','ftp://example.test','http://api.deepseek.com','https://user:pass@example.test','https://api.deepseek.com?key=secret','https://api.deepseek.com/#fragment'])assert.throws(()=>run('normalizeAnalysisEndpoint('+JSON.stringify(input)+')'));
 run("updateAnalysisMode('ai')");elements['analysis-endpoint'].value='https://api.example.test/v1';elements['analysis-model'].value='demo';elements['analysis-key'].value='dem';elements['analysis-custom-prompt'].value='Focus on support';
 elements['analysis-deepseek'].handlers.click();assert.strictEqual(elements['analysis-endpoint'].value,'https://api.deepseek.com');assert.strictEqual(elements['analysis-model'].value,'demo');assert.strictEqual(elements['analysis-key'].value,'dem');elements['analysis-endpoint'].value='https://api.example.test/v1';
 await run('prepareAnalysis()');assert(!elements['analysis-preview'].hidden);assert(elements['analysis-payload'].textContent.includes('SYSTEM\nSafe instructions\nUser focus: Focus on support\n\nUSER\n'+preview.batches[0].payloadText));assert(elements['analysis-payload'].textContent.includes('第 2 / 2 批'));assert(elements['analysis-payload'].textContent.includes(preview.batches[1].payloadText));assert(elements['analysis-payload'].textContent.includes('SYSTEM\nSynthesis evidence rules'));assert(elements['analysis-payload'].textContent.includes(preview.synthesis.payloadTemplate));assert(elements['analysis-preview-meta'].textContent.includes('https://api.example.test/v1/chat/completions'));assert(elements['analysis-preview-meta'].textContent.includes('拟发送全部 120 条有效文字'));assert(elements['analysis-preview-meta'].textContent.includes('分 2 批'));assert(elements['analysis-preview-meta'].textContent.includes('模型：demo'));assert(calls.filter(x=>x.path==='analysis/prepare').at(-1).body.customPrompt==='Focus on support');assert(elements['analysis-ai-start'].disabled);
 assert(elements['analysis-preview-meta'].textContent.includes('主框架：社会交换理论'));
 assert(elements['analysis-payload'].textContent.includes('中间综合 SYSTEM（需要分层时使用）\n'+preview.synthesis.intermediateSystemPrompt));
 elements['analysis-consent'].checked=true;elements['analysis-custom-prompt'].value='Focus on repairs';elements['analysis-custom-prompt'].handlers.input();assert(elements['analysis-preview'].hidden);assert(!elements['analysis-consent'].checked);assert(!run('analysis.previewId'));await run('prepareAnalysis()');assert(elements['analysis-payload'].textContent.includes('User focus: Focus on repairs'));
 elements['analysis-consent'].checked=true;run('refreshAnalysisReadiness()');assert(!elements['analysis-ai-start'].disabled);elements['analysis-key'].value='';await assert.rejects(()=>run('startPreparedAnalysis()'),/API 密钥输入框/);elements['analysis-key'].value='dem';await run('startPreparedAnalysis()');assert(elements['analysis-key'].value==='');assert(calls.filter(x=>x.path==='analysis/start').at(-1).body.consent===true);
 assert.strictEqual(calls.filter(x=>x.path==='analysis/start').at(-1).body.endpoint,'https://api.example.test/v1/chat/completions');assert.strictEqual(calls.filter(x=>x.path==='analysis/start').at(-1).body.apiKey,'dem');assert.strictEqual(calls.filter(x=>x.path==='analysis/start').at(-1).body.model,'demo');
 elements['analysis-key'].value='';for(const endpoint of ['http://localhost:8000/v1','http://127.0.0.1:8000/v1','http://[::1]:8000/v1']){elements['analysis-endpoint'].value=endpoint;assert.doesNotThrow(()=>run('validateAnalysisSettings(true)'));}elements['analysis-endpoint'].value='https://api.example.test/v1';assert.throws(()=>run('validateAnalysisSettings(true)'),/API 密钥输入框/);
 context.partialPreview={previewId:'partial',preview:{...preview,coverage:{...preview.coverage,mode:'partial',sentMessageCount:60,batchCount:1},batches:[preview.batches[0]],synthesis:{required:false}}};run('showAnalysisPreview(partialPreview)');assert(elements['analysis-preview-meta'].textContent.includes('拟发送 60 / 120 条有效文字'));assert(!elements['analysis-preview-meta'].textContent.includes('拟发送全部'));assert(!elements['analysis-payload'].textContent.includes('Synthesis evidence rules'));
 context.blockedPreview={previewId:'blocked',preview:{...preview,canUseAI:false,planningError:'A single message exceeds the complete-request size limit.'}};run('showAnalysisPreview(blockedPreview)');elements['analysis-consent'].checked=true;run('refreshAnalysisReadiness()');assert(elements['analysis-ai-start'].disabled);assert(!run('analysis.previewId'));assert(elements['analysis-error'].textContent===context.blockedPreview.preview.planningError);run('invalidateAnalysisPreview()');
 run("renderState({busy:true,operation:'analyze',status:'running',sessions:[],logs:[],analysisResult:true})");assert(!elements['analysis-stop'].hidden);assert(!elements['analysis-stop'].disabled);assert(elements['analysis-archive'].disabled);assert(elements['analysis-custom-prompt'].disabled);
 run("renderState({busy:true,operation:'analyze',status:'stopping',sessions:[],logs:[]})");assert(elements['analysis-stop'].disabled);
 run("renderState({busy:false,operation:null,status:'ready',sessions:[],logs:[]})");elements['analysis-archive'].value='bad';assert(!(await run('inspectAnalysisArchive()')));assert(elements['analysis-error'].textContent==='invalid archive');
 run("wechatSupported=false;voiceAvailable=false;platform='WeChat';mode='direct';updatePlatform()");assert.strictEqual(run('mode'),'import');assert(elements['import-hint'].textContent.includes('Mac'));assert(elements['install'].disabled);assert(elements['transcribe'].disabled);
 run("state={...state,wechatSupported:true,wechatMac:true,wechatInstalled:true,wechatReady:true,qceInstalled:true,qceInstallSupported:true};renderComponents(state);platform='WeChat';mode='direct';updatePlatform()");assert.strictEqual(run('mode'),'direct');assert(!elements['wechat-mac-setup'].hidden);assert(!elements['init-wechat'].disabled);assert(!elements['start-qq'].disabled);
 run("wechatSupported=true;voiceAvailable=true;refreshReadiness()");assert(!elements['install'].disabled);assert(!elements['transcribe'].disabled);
 run("state={wechatInstalled:true,wechatSupported:true,wechatMac:true,wechatPreflight:{blocked:true,code:'protected_client',title:'不支持直读',detail:'请导入'}};renderComponents(state);refreshReadiness()");assert(elements['init-wechat'].disabled);assert(elements['install-wechat-mac'].disabled);assert(!elements['wechat-import-route'].hidden);assert.strictEqual(elements['wechat-step-title'].textContent,'不支持直读');
 elements['wechat-import-route'].handlers.click();assert.strictEqual(run('mode'),'import');
 console.log('PASS: real app.js DOM smoke — navigation, QCE import identity, four templates, local generation, no sample limit, 10 accepted generic/DeepSeek endpoint forms, 6 rejected endpoint forms, preset preserves model/key, two exact batch requests plus synthesis preview, full-text coverage, editable prompt reconsent, short overlapping key/model remain separate, blank-key validation, secret clearing, cancellation state, bad archive. Help navigation, connection status, duplicate connection guard and guided QQ route also passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
